version: 1.0.{build}

branches:
  only:
  - master

image: Visual Studio 2015
platform: x64

clone_depth: 1

environment:
  matrix:
  - PYTHON: 36

install:
- ps: |
    if ($env:PLATFORM -eq "x64") {
        $env:PYTHON = "$env:PYTHON-x64"
        $env:VCPKG_DEFAULT_TRIPLET = "x64-windows"
    }

    $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
    python -m pip install --upgrade pip wheel
    vcpkg install eigen3

    if (-Not $env:BUILD_EXTERN) {
        vcpkg install glew libpng zlib libjpeg-turbo
    }

    $env:CMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build_script:
- python setup.py install

test_script:
- python -c "import pangolinpy"
